"""
SAMMed data loading (repo utils/prostate_resnet_bbox.py + sam_4_preprocessed_bbox.py).

Images/masks are read with utils.data_io (same as every other DG method) at
512x512 (the repo's Prostate dataset also loads at 512). The repo's Prostate
preprocessing is reproduced exactly: per-sample min-max normalization,
round(*255) -> uint8 and histogram equalization (torchvision equalize) on
every slice (both stages - resnet and SAM - consume these images). Each
sample carries the refined bounding box [x_min, y_min, x_max, y_max]
generated by the source-trained segmentation backbone (mask-filtering
module, saved as .npy) instead of the benchmark box_coords.json - SAMMed
has its own prompting mechanism. A small random perturbation (+-10 px) is
applied to the box at training time exactly like the repo's _get_bbox.

The "merging strategy" (paper Sec. 3.4 / repo training loop): four 512x512
images are concatenated into a 1024x1024 composite (2x2 grid) so that SAM's
pre-trained image encoder runs at its native resolution, and the boxes /
ground-truth masks are shifted accordingly.
"""
import hashlib
import os

import numpy as np
import torch
from torch.utils.data import Dataset
from torchvision.transforms import functional as tf

from utils.data import _make_loader, get_datasets
from utils.data_io import read_image_mask

IMAGE_SIZE = 512        # per-patch resolution (repo prostate loads at 512)
SAM_SIZE = 1024         # SAM native resolution of the merged composite
GRID = 2                # 2x2 grid of patches per composite
PATCH_NUM = GRID * GRID

BOX_ROOT = 'weights/sammed/bboxes'


def _image_id(image_path):
    return hashlib.md5(image_path.encode('utf-8')).hexdigest()[:16]


def preprocess_image(image):
    """Repo Prostate.__getitem__ preprocessing (utils/prostate.py and
    utils/prostate_resnet_bbox.py): min-max normalize, *255 round -> uint8,
    histogram equalize, /255. Input: (C, H, W) float tensor in [0, 1]."""
    min_val = image.min()
    max_val = image.max()
    image = (image - min_val) / (max_val - min_val + 1e-8)
    image = torch.round(image * 255).to(torch.uint8)
    image = tf.equalize(image)
    return image / 255.0


def box_save_dir(src_name, dst_name, thresh):
    return os.path.join(BOX_ROOT, f'src_domain_idx_{src_name}_{int(thresh * 100)}',
                        dst_name)


class SAMMedDataset(Dataset):
    """Single-source dataset with refined bbox prompts.

    Returns (image [3,512,512], mask [1,512,512], bbox [4], id) per slice.
    """

    def __init__(self, images, masks, box_dir, perturb=False, image_size=IMAGE_SIZE):
        self.images = images
        self.masks = masks
        self.box_dir = box_dir
        self.perturb = perturb
        self.image_size = image_size
        self.ids = [_image_id(p) for p in images]

    def __len__(self):
        return len(self.images)

    def _get_bbox(self, img_id, mask):
        if self.box_dir is None:
            return torch.zeros(4, dtype=torch.float32)
        path = os.path.join(self.box_dir, img_id + '.npy')
        if os.path.exists(path):
            box = np.load(path).astype(np.float32)
        else:
            box = np.zeros(4, dtype=np.float32)
        if self.perturb:
            H, W = self.image_size, self.image_size
            box = box.copy()
            box[0] = max(0, box[0] - np.random.randint(0, 10))
            box[2] = min(W, box[2] + np.random.randint(0, 10))
            box[1] = max(0, box[1] - np.random.randint(0, 10))
            box[3] = min(H, box[3] + np.random.randint(0, 10))
        return torch.as_tensor(box, dtype=torch.float32)

    def __getitem__(self, i):
        image, mask = read_image_mask(self.images[i], self.masks[i], self.image_size)
        image = preprocess_image(image)
        bbox = self._get_bbox(self.ids[i], mask)
        return image, mask, bbox, self.ids[i]


def merge_batch(images, masks, boxes, image_size=IMAGE_SIZE, sam_size=SAM_SIZE,
                grid=GRID):
    """Merge a batch of B = k * grid^2 patches into k composite images.

    Boxes (B, 4) in patch-space are rescaled to SAM-space and shifted by
    their patch offsets in the composite (paper Sec. 3.4).
    """
    B, C, H, W = images.shape
    patch_num = grid * grid
    mbz = B // patch_num
    row_num = grid
    col_num = grid

    merged_images = torch.zeros(mbz, C, sam_size, sam_size, device=images.device)
    merged_masks = torch.zeros(mbz, 1, sam_size, sam_size, device=images.device)
    box_tensor = boxes.clone() * (sam_size / image_size)

    for idx in range(mbz):
        for i in range(row_num):
            for j in range(col_num):
                bz_idx = idx * patch_num + i * col_num + j
                merged_images[idx, :, i * image_size:(i + 1) * image_size,
                              j * image_size:(j + 1) * image_size] = images[bz_idx]
                merged_masks[idx, :, i * image_size:(i + 1) * image_size,
                             j * image_size:(j + 1) * image_size] = masks[bz_idx]
                box_tensor[bz_idx][0] += sam_size / grid * j
                box_tensor[bz_idx][1] += sam_size / grid * i
                box_tensor[bz_idx][2] += sam_size / grid * j
                box_tensor[bz_idx][3] += sam_size / grid * i
    return merged_images, merged_masks, box_tensor, mbz, row_num, col_num


def unmerge_batch(merged_masks, mbz, row_num, col_num, image_size=IMAGE_SIZE,
                  sam_size=SAM_SIZE):
    """Reconstruct per-patch predictions from merged composites."""
    B = mbz * row_num * col_num
    C = merged_masks.shape[1]
    out = torch.zeros(B, C, image_size, image_size, device=merged_masks.device)
    for idx in range(mbz):
        for i in range(row_num):
            for j in range(col_num):
                bz_idx = idx * row_num * col_num + i * col_num + j
                out[bz_idx] = merged_masks[idx, :, i * image_size:(i + 1) * image_size,
                                           j * image_size:(j + 1) * image_size]
    return out


def _collect_split(name, image_size, split):
    train_ds, valid_ds, test_ds = get_datasets(name=name, image_size=image_size, transform=None)
    ds = {'train': train_ds, 'val': valid_ds, 'test': test_ds}[split]
    return ds.images, ds.masks


def get_sammed_loaders(source_name, box_dir, image_size, batch_size,
                       num_workers, pin_memory):
    """Train/val loaders for the SAM stage of one source domain."""
    train_imgs, train_masks = _collect_split(source_name, image_size, 'train')
    print(f'Dataset: {source_name} | Source train: {len(train_imgs)}')
    val_imgs, val_masks = _collect_split(source_name, image_size, 'val')
    print(f'Dataset: {source_name} | Source val: {len(val_imgs)}')

    train_dataset = SAMMedDataset(train_imgs, train_masks, box_dir, perturb=True,
                                  image_size=image_size)
    val_dataset = SAMMedDataset(val_imgs, val_masks, box_dir, perturb=False,
                                image_size=image_size)

    train_loader = _make_loader(train_dataset, batch_size, shuffle=True,
                                num_workers=num_workers, pin_memory=pin_memory,
                                drop_last=True)
    val_loader = _make_loader(val_dataset, batch_size, shuffle=False,
                              num_workers=num_workers, pin_memory=pin_memory)
    return train_loader, val_loader


def get_sammed_target_loader(target_name, box_dir, image_size, batch_size,
                             num_workers, pin_memory, split='test'):
    """Target loader with refined box prompts (split='test' by default)."""
    imgs, masks = _collect_split(target_name, image_size, split)
    dataset = SAMMedDataset(imgs, masks, box_dir, perturb=False, image_size=image_size)
    loader = _make_loader(dataset, batch_size=batch_size, shuffle=False,
                          num_workers=num_workers, pin_memory=pin_memory)
    return loader


def get_resnet_loaders(source_name, image_size, batch_size, num_workers,
                       pin_memory):
    """Train/val loaders for the stage-1 segmentation backbone."""
    train_imgs, train_masks = _collect_split(source_name, image_size, 'train')
    print(f'Dataset: {source_name} | Resnet train: {len(train_imgs)}')
    val_imgs, val_masks = _collect_split(source_name, image_size, 'val')
    print(f'Dataset: {source_name} | Resnet val: {len(val_imgs)}')

    train_dataset = SAMMedDataset(train_imgs, train_masks, box_dir=None,
                                  perturb=False, image_size=image_size)
    val_dataset = SAMMedDataset(val_imgs, val_masks, box_dir=None,
                                perturb=False, image_size=image_size)

    train_loader = _make_loader(train_dataset, batch_size, shuffle=True,
                                num_workers=num_workers, pin_memory=pin_memory,
                                drop_last=True)
    val_loader = _make_loader(val_dataset, batch_size, shuffle=False,
                              num_workers=num_workers, pin_memory=pin_memory)
    return train_loader, val_loader


def get_resnet_dataset(name, image_size, split):
    """Raw (images, masks) lists of a split for bbox generation."""
    imgs, masks = _collect_split(name, image_size, split)
    ids = [_image_id(p) for p in imgs]
    return imgs, masks, ids
